spring:
  datasource:
    url: jdbc:postgresql://database-e874374f-6547-40ab-ac7a-2742f7938268.dyn.mayope.net:5432/lukas-test?user=postgres&password=cdBYxd5uuUOxKa4DPgqc&sslmode=require&ssltermination=proxy
  jpa:
    hibernate:
      ddl-auto: update
project:
  description: todoapp
