spring:
  datasource:
    url: jdbc:postgresql://database-6ba7d894-a618-487b-b1dd-4ca9d96abe6a.dyn.mayope.net:5432/my?user=postgres&password=password&sslmode=require&ssltermination=proxy
  jpa:
    hibernate:
      ddl-auto: update
project:
  description: todoapp
